server:
  port: 60000

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: true
