server:
  port: 60000

spring:
  application:
    name: user-service

eureka:
  client:
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true
